### ISSUE TITLE
REQUEST: _run_PostMut (chk_mutdet.sh) should allow alternate patient_id_conversions.tsv files

### ISSUE THREAD

**Issue by shuntsman-ucsf** [UCSF-Costello-Lab/LG3_Pipeline#102]
_run_PostMut will fail if you are trying to override the filename when calling the script.

Specificaly, chk_mutdet.sh contains a line 32:
`CONV=patient_ID_conversions.tsv`
that hardcodes the filename.

This is inconvenient if you have to deal with multiple tumors or normals that need merging, since you will use a different patient_ID_conversions file in the steps after Recal, and it is safer to keep the original conversions file as the original name if some samples are still running earlier steps and use a different name in the later steps to avoid conflicting.

Can you add in the usual functionality to allow for overriding `CONV=${CONV:-patient_ID_conversions.tsv}` and remove line 32 from chk_mutdet.sh?

Preferably soon as part of 2018-10-17-patched?

**Comment by HenrikBengtsson** [comment]
Thanks.  Now fixed in the patched (and develop) version.
