### ISSUE TITLE
BUG: scratch disk directories are not completely removed after job is done

### ISSUE THREAD

**Issue by ivan108** [UCSF-Costello-Lab/LG3_Pipeline#103]
directories like 
/scratch/jocostello/1228305.cclc01.som.ucsf.edu are not deleted after job is done

**Comment by ivan108** [comment]
I fixed Recal*.pbs scripts, by adding in the end:

```
echo "Cleaning: rm ${LG3_SCRATCH_ROOT} ..."
rm -rf "${LG3_SCRATCH_ROOT}"
```

**Comment by HenrikBengtsson** [comment]
Has this been resolved and tested?  Or are there more occurrences that needs to be fixed before closing?

**Comment by ivan108** [comment]
Still working on it... Just finished pindel_all.pbs, it was somewhat messy, some calculations were done in scratch space, others directly on the file server...

**Comment by ivan108** [comment]
Fixed post_mutect_pindel.pbs, which wasn't using SCRATCH, now it does, except scripts/runLOH_ivan.sh script. Looks a little too complex to make it use the SCRATCH...
Anyway, it doesn't contaminate SCRATCH, so the issue can be closed for now.
We could open another issue, to make all scripts to use SCRATCH, if we wanted to...

**Comment by HenrikBengtsson** [comment]
Sounds good. Also, if there's not much intermediate disk I/O in the step, there's no need to work toward scratch.

Don't forget to update NEWS; this one would go under BUG FIXES I think.

**Comment by HenrikBengtsson** [comment]
It looks like you update NEWS for the already released version.

**Comment by HenrikBengtsson** [comment]
I'm reopening so that the wrongly placed NEWS entry is not forgotten.

**Comment by ivan108** [comment]
I just edited my local NEWS.md on develop, what is the right one to update?

**Comment by HenrikBengtsson** [comment]
Right file but bullet point in wrong location. Move it up under "Version 2018-10-27-9000"

**Comment by ivan108** [comment]
Got it :)

**Comment by HenrikBengtsson** [comment]
I see you've moved it up, but look also on all previous versions.  The 'BUG FIXES' section should come after 'NEW FEATURES'.

**Comment by ivan108** [comment]
I see that now, thanks!

**Comment by HenrikBengtsson** [comment]
The below "readlink" [addition](https://github.com/UCSF-Costello-Lab/LG3_Pipeline/blame/develop/scripts/mutdet_submit.sh#L75) of:
```r
WORKDIR=${LG3_OUTPUT_ROOT}/${PROJECT:?}/mutations/${PATIENT}_mutect
WORKDIR=$(readlink -e "${WORKDIR}")
mkdir -p "${WORKDIR}" || error "Can't create scratch directory ${WORKDIR}"
```
broke the pipeline, because `WORKDIR` doesn't exist at this point in time resulting in an empty `WORKDIR` variable causing `mkdir` to fail.

Even if the simplest tweaks, please don't forget to run through the pipeline test.

I've fixed this in commit 0909cbd.

**Comment by HenrikBengtsson** [comment]
After fixing above `WORKDIR` hiccup, `./run_MutDet` runs, but now fails at the very end with:
```sh
[Annotate] Identify cancer genes...

real    0m1.052s
user    0m0.954s
sys     0m0.062s
30 Patient157t10.NOR-Z00599t10__REC1-Z00601t10.annotated.mutations
[Annotate] Finished!
-------------------------------------------------
All done! Mon Nov  5 09:41:33 PST 2018
[2018-11-05 09:41:33 PST] END: /cbc2/data2/henrik/repositories/UCSF-CostelloLab/LG3_Pipeline-devel/scripts/MutDet.sh
Copy results from /scratch/henrik/1236813.cclc01.som.ucsf.edu/Patient157t10_mutect to output/LG3/mutations/Patient157t10_mutect
ERROR: Fail to copy results to output/LG3/mutations/Patient157t10_mutect
Traceback:
1: main() on line #104 in /var/spool/torque/mom_priv/jobs/1236813.cclc01.som.ucsf.edu.SC
Exiting (exit 1)
```

**Comment by ivan108** [comment]
Good catch! What hapened is that I moved calculation to scratch, as a result WORKDIR needs absolute path before it is passed to MutDet_TvsN.pbs:
scripts/mutdet_submit.sh:
```
WORKDIR=${LG3_OUTPUT_ROOT}/${PROJECT:?}/mutations/${PATIENT}_mutect
WORKDIR=$(readlink -e "${WORKDIR:?}") ## Added absolute path
```

**Comment by HenrikBengtsson** [comment]
Ok, so what about using `readlink` *after* `mkdir`?

**Comment by ivan108** [comment]
I don't mind.. What is the advantage?

**Comment by HenrikBengtsson** [comment]
I tried to explain that above, e.g.
```sh
$ WORKDIR=non-existing/folder
$ echo $WORKDIR
non-existing/folder
$ WORKDIR=$(readlink -e "${WORKDIR:?}")
$ echo $WORKDIR  ## here WORKDIR is empty!
$
```

**Comment by ivan108** [comment]
You are right!

**Comment by HenrikBengtsson** [comment]
I've run through the pipeline. It works now.
