### ISSUE TITLE
Unused code?

### ISSUE THREAD

**Issue by ivan108** [UCSF-Costello-Lab/LG3_Pipeline#110]
See _run_MutDet line 51:

`export QSUB_OPTS`

but QSUB_OPTS is not set? Do we need this line?

**Comment by HenrikBengtsson** [comment]
Probably not.

FYI, you can link to code and specific lines, blocks of lines, using Markdown format:
```r
[_run_MutDet](https://github.com/UCSF-Costello-Lab/LG3_Pipeline/blob/master/runs_demo/_run_MutDet#L45)
```
or as plain URLs,
```
<https://github.com/UCSF-Costello-Lab/LG3_Pipeline/blob/master/runs_demo/_run_MutDet#L45>
```
as in:

* [_run_MutDet](https://github.com/UCSF-Costello-Lab/LG3_Pipeline/blob/master/runs_demo/_run_MutDet#L45)
* <https://github.com/UCSF-Costello-Lab/LG3_Pipeline/blob/master/runs_demo/_run_MutDet#L45>

**Comment by HenrikBengtsson** [comment]
Actually, we do indeed need that `export` in some cases, cf. Issue #82.

**Comment by HenrikBengtsson** [comment]
I've added it back - now with a comment explaining why it should be there.
