### ISSUE TITLE
WISH: Is there an existing identity check for tumor/normal samples?

### ISSUE THREAD

**Issue by shuntsman-ucsf** [UCSF-Costello-Lab/LG3_Pipeline#116]
Is there any part of the pipeline that currently checks if the samples you are using as tumor/normal have sufficient concordance that they are properly paired tumor/normal and not a sample mixup?  We have a few patients with excessive numbers of mutations found that we suspect are sample mixups and will check, but wondering first if that info would already be found somewhere in the pipeline results.

**Comment by ivan108** [comment]
Yes, germline relatedness analysis is included in Recal step. The output should be in "germline" subdirectory of the Recal output. It includes the VCF file with germline mutations for all samples of the patient, and *.germline file for each tumor-normal pair, showing how much germline mutations are retained in tumor compared to normal. Usually it is over 99%...
