### ISSUE TITLE
ERRORS: make check errors

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-Costello-Lab/LG3_Pipeline#118]
@ivan108, pls pls pls make sure `make check` always passes without errors.  The [![Build Status](https://travis-ci.org/UCSF-Costello-Lab/LG3_Pipeline.svg?branch=develop)](https://travis-ci.org/UCSF-Costello-Lab/LG3_Pipeline) on the front page shows that Travis CI detects these [errors](https://travis-ci.org/UCSF-Costello-Lab/LG3_Pipeline) too.
```
0.02s$ make check
Miscellaneous code inspections:
- Assert no hardcoded email address
- Assert no hardcoded /LG3/ project paths
make: *** [check_misc] Error 1
The command "make check" exited with 2.
```

**Comment by ivan108** [comment]
Oops, totally forgot about this wonderful tool :)
Fixed now.

**Comment by HenrikBengtsson** [comment]
Thxs.
