### ISSUE TITLE
BUG: /home/ismirnov/install/trim_galore/v0.4.4/trim_galore: Permission denied

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-Costello-Lab/LG3_Pipeline#12]
While running tests on a bare-bone fresh cluster account (cbctest2), I got:
```sh
/home/cbctest2/repositories/LG3_Pipeline/scripts/trim_galore.sh: line 68: /home/ismirnov/install/trim_galore/v0.4.4/trim_galore: Permission denied
```

@ivan108, what do you suggest?  Should we move this installation to another location, or are you willing to open out access to that path?

**Comment by HenrikBengtsson** [comment]
I've just installed TrimGalore 0.4.4 publicly accessible under:
```sh
$ ls -l /home/shared/cbc/software_frozen/20180907-LG3_Pipeline/TrimGalore-0.4.4
total 124
-rw-r--r-- 1 henrik cbc 10111 Mar 28  2017 Changelog.md
drwxr-sr-x 3 henrik cbc    88 Mar 28  2017 Docs
-rw-r--r-- 1 henrik cbc 35141 Mar 28  2017 LICENSE
-rw-r--r-- 1 henrik cbc  1720 Mar 28  2017 README.md
drwxr-sr-x 2 henrik cbc  4096 Mar 28  2017 test_files
-rwxr-xr-x 1 henrik cbc 67419 Mar 28  2017 trim_galore
```

**Comment by ivan108** [comment]
I think moving all software to public domain is a good idea. Do we need to load corresponding module or use the path?

**Comment by HenrikBengtsson** [comment]
This is what I think needs to be done/path forward/long-term solution:
1. Identify all software tools currently used, cf. Issue #10
2. Freeze those in a single central location, e.g. /home/shared/cbc/software_frozen/20180907-LG3_Pipeline
3. Include run-time sanity tests ("contracts") that assert that we really running these frozen versions.
4. For legacy versions of programming languages (e.g. Python, Java, R), migrate to latest stable versions.
5. For legacy versions of sequencing tools, try to migrate to newer versions.  For some tools we know there will be major problems, e.g. GATK.

Working through these steps require solid testing to make sure things don't break and results are reproducible.  So, testing testing testing...

More comments: Yes, we can also introduce software modules for controlling the above, e.g. `module load lg3-pipeline`, but lets not worry about that for now.

**Comment by ivan108** [comment]
This brings back the topic of testing dataset. We can try to use a dataset trimmed to a single small chromosome (chr20?) with fair number of exomes, from a patient containing a lot of verified mutations in tumor samples ...

**Comment by HenrikBengtsson** [comment]
I think that would be wonderful. You might wanna use two chromosomes to cover the test of multiple chromosomes. Could you please create a separate issue for this? (I like to keep Issues/tasks as small as possible to keep focus and be able to actually close them)

**Comment by HenrikBengtsson** [comment]
Fixed the original issue.  The task on consolidating the software stack to one location has been moved to Issue #17.
