### ISSUE TITLE
BUG(?): R_LIBS_USER=~/R/%p-library/%v /opt/R/R-latest/bin/Rscript: No such file or directory

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-Costello-Lab/LG3_Pipeline#125]
@ivan108 [reported](https://github.com/UCSF-Costello-Lab/LG3_Pipeline/issues/122#issuecomment-484598048):

 ```sh
mkdir lg3-demo
cd lg3-demo
lg3 --version
2019-03-23 (commit 749df93)
mkdir output
export PATIENT=Patient157t10
lg3 test setup
*** Setup
[OK] LG3_HOME: /home/shared/cbc/software_cbc/LG3_Pipeline-2019-03-23
/home/shared/cbc/software_cbc/LG3_Pipeline-2019-03-23/bin/lg3-test: line 244: R_LIBS_USER=~/R/%p-library/%v /opt/R/R-latest/bin/Rscript: No such file or directory
[... other tests are OK]]
```

**Comment by HenrikBengtsson** [comment]
This is a bug in the sense that:

https://github.com/UCSF-Costello-Lab/LG3_Pipeline/blob/749df93e4060bdc6a1e6f3599da2e24bcc611eee/bin/lg3-test#L244

assumes that the user has already set up a personal R package library at the default location, which all users who run:
```r
> install.packages(...)
```
at least once and accepts the inquiry by R to create and install to the default user-specific R library path.

**Comment by HenrikBengtsson** [comment]
Actually, after further investigation, blaming `R_LIBS_USER` not existing was wrong; that line creates it if it is missing.  Instead, I suspect that error:
```
/home/shared/cbc/software_cbc/LG3_Pipeline-2019-03-23/bin/lg3-test: line 244:
R_LIBS_USER=~/R/%p-library/%v /opt/R/R-latest/bin/Rscript: No such file or directory
```
is about `/opt/R/R-latest/bin/Rscript` to being found.  I've added an explicit assertion about this before trying to call that Rscript binary, cf. commit 1b1baf64

**Comment by HenrikBengtsson** [comment]
@ivan108, what machine where you running on for this error to occur?

**Comment by ivan108** [comment]
I was running on head node from ismirnov account.
I tried to re-run 
`lg3 test setup`
and no errors were detected...

I continue to run test pipeline, currently _run_Recal step. When it is done, I will create empty ./lg3.conf file with single line:
PINDEL_NEW=true
and see what happens when I run _run_Pindel ...

**Comment by ivan108** [comment]
PS: may be an empty ./lg3.conf file should be created while running
`lg3 test setup`
?

**Comment by ivan108** [comment]
May be not completely empty, but with some comments in headers explaining what is this file for..?

**Comment by HenrikBengtsson** [comment]
Please add comments to the correct issue otherwise it'll be impossible to close issues and find our own reasoning when we get back to it in the future.
