### ISSUE TITLE
Test dataset for exome pipline

### ISSUE THREAD

**Issue by ivan108** [UCSF-Costello-Lab/LG3_Pipeline#13]
We can try to use a dataset trimmed to a single small chromosome (chr20?) or two with fair number of exomes, from a patient containing a lot of verified mutations in tumor samples ...

**Comment by ivan108** [comment]
So, I created a subset of Patient157 (Patient157t) dataset which has only 2 chomosomes: chr17 and chr19 in each of 3 samples. From the original run we expect to detect a total of 17 mutations: 15 SNPs detected by MuTect and 2 InDels detected by Pindel. I ran this dataset through develop pipeline, and detected 16 same mutations, one is missing. Total run time is ~25h, compared to ~132h for the full dataset! The only little issue remains is that the last stage which generates LOH plots has failed. I suspect it is trying to plot all chromosomes even when there is no data. I will look into that ...

**Comment by HenrikBengtsson** [comment]
Brilliant. This will be very useful.  I should be only a few hours away from completing the Recal step on the full sample.

**Comment by ivan108** [comment]
I just updated develop branch to use 2chr dataset for test runs...

**Comment by HenrikBengtsson** [comment]
Thanks. FYI, I've just started testing with this over in the [features/envvars-t](https://github.com/UCSF-Costello-Lab/LG3_Pipeline/tree/feature/envvars-t) branch.  I've generalized the test run scripts so they take env vars as input and can therefore be used for both the full and the two-chr dataset.

**Comment by HenrikBengtsson** [comment]
Good news here!  I've now managed to complete Steps 1-7 and from a quick inspection it seems that I get the same set of identified markers as in https://github.com/UCSF-Costello-Lab/LG3_Pipeline/blob/develop/runs_demo/Patient157t.R.mutations

I'll have a small coffee break to gather my thoughts, do some minor cleanups and then I'll ask you to test the pipeline on your end - will continue that topic over in Issue #15.  Stay tuned...
