### ISSUE TITLE
Test Round 2: Making sure things still work the same also after my updates

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-Costello-Lab/LG3_Pipeline#15]
@ivan108, I've just push a new branch [tests/round2](https://github.com/UCSF-Costello-Lab/LG3_Pipeline/tree/tests/round2).  It contains my modifications for Issue #3.

It works on my end.  Could you please test the first two steps there to make sure I haven't broken anything in relationship to how you normally run the pipeline:
```sh
$ git pull
$ git checkout tests/round2
Switched to branch 'tests/round2'
Your branch is up to date with 'origin/tests/round2'.
```
It's important that you really are on this branch when testing, so please doublecheck.

Then just run:

* [x] `./_run_Trim_P157`
* [x] `./_run_Align_gz_P157`

as you've done in the past.  When those have finished for you, I think I'm ready to give you also the new `_run_Recal_P157_3` (currently 45 hours into my test run).

**Comment by HenrikBengtsson** [comment]
At the time when I created tests/round2 I merged what's in the develop branch, but I haven't merge since.   
 Nothing is automatically merged in git.  

Here's what the repos looks like right now (colored nicely in the terminal):
```sh
$ git pull -all
$ git log --graph --oneline --all
*   34f1aaf (HEAD -> develop, origin/develop) Merge branch 'develop' of github.com:UCSF-Costello-Lab/LG3_Pipeline into develop
|\  
* | 658f3d5 removed chastity filtering
| | * 81ff3a3 (origin/tests/round2, origin/feature/envvars, feature/envvars) tweak
| | * b5d94d7 TESTS: Add validation of output from step3 and step4
| | * d53602b FIX: Can only assert for the folder of the BWA_INDEX
| | * 8da05b6 fix
| | * 40e01a7 Using ncores=${PBS_NUM_PPN:1} + another absolute instead of relative path [#14]
| | * 20b0f6a ROBUSTNESS: Assert that output / working directories can be created
| | * 7afcfc9 ROBUSTNESS: Assert that scripts and input files exist
| | * 986b2dd ROBUSTNESS: Run scripts now assert that scripts and input files/folders exist
| | *   3b6f4a0 Merge branch 'develop' into feature/envvars
[...]
```
BTW, I guess you haven't pushed your commits - because I see nothing about the new test files.


I recommend that you finish the testing on your end and I finish mine.  Note that a really good side effect of moving away from the hardcoded paths is that we can run multiple tests in parallel and we can even test different versions in parallel.

BTW2, unless you find it really necessary, please avoid updating the existing code too much.  I've done lots of edits (all minimal but required) and whatever edits you do on the same files will most likely require manual merging.

**Comment by ivan108** [comment]
Test dataset is not tracked by git, it is just another dataset. But we could include the script which makes test dataset from the original full dataset.. 

I only modified scripts/Align_fastq.sh file, removed chastity filtering of input fastq files, because it is not compatible with fastqs extracted from bam, only with original Illumina fastqs...

**Comment by HenrikBengtsson** [comment]
> Test dataset is not tracked by git, it is just another dataset. But we could include the script which makes test dataset from the original full dataset..

I was looking for changes in filenames.

Lets keep only code in this repos - adding data files or reference files would make it blow up in size - we don't want that.  Later we might create a separate 'LG3_Pipeline_ExampleData' repos.

> I only modified scripts/Align_fastq.sh file, removed chastity filtering of input fastq files, because it is not compatible with fastqs extracted from bam, only with original Illumina fastqs...

ok.  So for my clarification, you needed to do this in order to work with the two-chromosome test data files, correct?

**Comment by HenrikBengtsson** [comment]
> I was looking for changes in filenames.

... in the scripts.

**Comment by ivan108** [comment]
... yes, for the two-chromosome test data , or any input data which is not in the fastq format, e.g. BAM, from which reads needs to be extracted in fastq format. In other words, fastq file produced from bam file is not quite the same as original Illumina fastq. Or may be there are better BAM-to-FastQ converters out there?

As for run_demo scripts, I will update them to use test dataset as soon as I finish testing it..

**Comment by HenrikBengtsson** [comment]
I've done more edits since and I've just started re-testing with your 2chr dataset and since it's much faster to complete, let's hold back on that one. I'll report back here when I think you can run it again.

**Comment by HenrikBengtsson** [comment]
Ok, let's try it.  I've updated the [`tests/round2`](https://github.com/UCSF-Costello-Lab/LG3_Pipeline/tree/tests/round2) branch which is now ready to be tested.  You should be able to test using by first doing:
```sh
$ cd /home/jocostello/shared/LG3_Pipeline
$ git fetch
$ git checkout tests/round2
$ git pull
```
Use the same setup as before (= creating the different resource links etc) which the difference:
```sh
$ cd /home/jocostello/shared/LG3_Pipeline
$ ln -fs runs_demo/_run_Trim
$ ln -fs runs_demo/_run_Align_gz
$ ln -fs runs_demo/_run_Recal
$ ln -fs runs_demo/_run_Pindel
$ ln -fs runs_demo/_run_MutDet
$ ln -fs runs_demo/_run_PostMut
```
Note that I've dropped the `_P157`/`_P157t` suffix (*).

Then, to actually run the tests, use:
```sh
$ cd /home/jocostello/shared/LG3_Pipeline
$ ./_run_Trim
$ ./_run_Align_gz
$ ./_run_Recal
$ ./_run_Pindel
$ ./_run_MutDet
$ ./_run_PostMut
```

I've verified that the above works when overriding `LG3_HOME`, `LG3_INPUT_ROOT`, and `LG3_OUTPUT_ROOT` (cf. https://github.com/UCSF-Costello-Lab/LG3_Pipeline/tree/tests/round2/tests/).  However, I want to make sure it still works in the existing production setup (without setting those env vars).


(*) I've generalized the scripts enough so it's easy to override what samples are run by using env vars - have a look at the scripts or just ignore it for now.  I did it so I can easily run both the full and the small test set.

**Comment by ivan108** [comment]
OK, I did as you said, and launched _run_Trim and got errors:

ERROR: Can't open Z00599t from rawdata/
ERROR: Can't open Z00600t from rawdata/
ERROR: Can't open Z00601t from rawdata/

which makes sense since I don't have rawdata directory. 
Is the idea to make symbolic link rawdata pointing to actual fastq repository or re-define LG3_INPUT_ROOT variable ? How?

**Comment by HenrikBengtsson** [comment]
Ah... yes, create a symbolic link:
```r
$ ln -fs /costellolab/data1/ismirnov/tmp rawdata
```

BTW, do you use `/costellolab/data1/ismirnov/tmp` as the default in production, or do you [set `RAW` for each new run script](https://github.com/UCSF-Costello-Lab/LG3_Pipeline/blob/master/runs_demo/_run_Trim_P157#L3) you create?

**Comment by ivan108** [comment]
OK, symbolic link rawdata works so far, finished _run_Trim ...

/costellolab/data1/ismirnov/tmp is the default repository of the original and trimmed fastqs, or links to them. It is needed only for _run_Trim and _run_Align_gz ... Or may be I didn't quite get your question?

**Comment by HenrikBengtsson** [comment]
I didn't mean just you test run script, but for you everyday processing.  If you always use `RAW=/costellolab/data1/ismirnov/tmp`, I'll make that the default instead of `./rawdata`.  (Again, this is just for the next release; after that we can discuss changes).

**Comment by ivan108** [comment]
I like rawdata as symlink, the actual location may be different for different projects...

**Comment by HenrikBengtsson** [comment]
Ok, then let's keep it.

**Comment by ivan108** [comment]
I am receiving a lot of email notifications about finished jobs, is there a reason you are using my address... How would one change email or any other variable in the pipeline?

**Comment by HenrikBengtsson** [comment]
The default is your email address but can be overridden by env var [`EMAIL`](https://github.com/UCSF-Costello-Lab/LG3_Pipeline/blob/feature/envvars/NEWS.md).  Let's make that a required env var in the next round (again, I didn't want to break anything for you), e.g. an `EMAIL=${EMAIL:?}` will then cause an error (didn't know before ShellCheck taught me about that one).

I was running is so many different terminals so it could have been that I've missing to set `EMAIL` - sorry about that.  It could also be that `EMAIL` is not passed along for all PBS scripts.  When making `EMAIL` a requirement, this will automatically be detected.

**Comment by HenrikBengtsson** [comment]
So, your testing is almost complete.  Don't forget to run the last step `_run_PostMut`.  Then we can release this version.

After that we can start working on all the other tasks, but let's wrap this one up.

**Comment by HenrikBengtsson** [comment]
I see you've created:
```sh
$cd /home/jocostello/shared/LG3_Pipeline
$ ls -l output
lrwxrwxrwx 1 jocostello costellolab 46 Sep 16 10:12 output -> /costellolab/data1/jocostello/LG3/exomes_recal
```
That shouldn't be there.  If a step doesn't run without it, then there's a bug that needs to be fixed.

**Comment by HenrikBengtsson** [comment]
I found two bugs when it comes to `LG3_INPUT_ROOT` settings.  This affected:

* `_run_Recal`
* `_run_Pindel`

I'm not sure if you're there, but if I don't hear from you within 10 minutes, I'll simply sudo in as joe and rerun those steps - I wanna run `_run_Recal` overnight so that can finish by Monday noon.

**Comment by HenrikBengtsson** [comment]
`_run_Pindel` just completed running as joe.  Are you seeing my comments here?   Are you also testing?  I see you edited `run_MutDet`? ... but nothing is running.

**Comment by HenrikBengtsson** [comment]
My bad, `_run_MutDet` was edited a few days ago.  I've just reset it and launched the `_run_MutDet` step.

**Comment by ivan108** [comment]
Sorry, I had limited access to computer over weekend, so I  am a little behind with testing. I had problems with pindel's path. Re-testing now..

**Comment by HenrikBengtsson** [comment]
Ok. No, read my comments.

**Comment by ivan108** [comment]
So, where are we now? I see you are running Mutect jobs as joe, and I am re-running Pindel, I deleted the previous output, but this won't take long...

**Comment by HenrikBengtsson** [comment]
Ok, if already confirmed _run_Pindel as joe - see https://github.com/UCSF-Costello-Lab/LG3_Pipeline/issues/15#issuecomment-422034591.  I'm running the _run_MutDet tests.  When that completes, there is only that quick _run_PostMut left.

**Comment by HenrikBengtsson** [comment]
Wow. From a quick look, it looks like we reach a milestone.  Do you see anything funny?  Can we wrap this one up and freeze it for a new release?

**Comment by ivan108** [comment]
Yes! Patient157t.R.mutations file looks exactly as the reference...

**Comment by HenrikBengtsson** [comment]
Awesome. I'll do the release now.  Stay tuned.

**Comment by HenrikBengtsson** [comment]
LG3_Pipeline v2018-09-17 just release, i.e.

* master branch now hold this latest stable release, e.g. `git clone git@github.com:UCSF-Costello-Lab/LG3_Pipeline.git`
* the version was tagged, e.g. `git checkout 2018-09-17` (previous was one you verified is `git checkout 2018-08-28`)
* develop branch is now up-to-date with master + 1 minor commit.

All other branches have been removed from GitHub.  You can now start working in develop.
