### ISSUE TITLE
assert_pwd: It's there for a reason

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-Costello-Lab/LG3_Pipeline#154]
I see that [you disabled](https://github.com/UCSF-Costello-Lab/LG3_Pipeline/commit/85abc1440dc387f661fe7f129c1d4815f69b83e2#diff-1615c06ff867567fde8b4caed7973fae157a4e384ebb043edc20cd2dd3a67bb1) the `assert_pwd` validation.  Like I said in https://github.com/UCSF-Costello-Lab/LG3_Pipeline/issues/153#issuecomment-933967687, please assume everything is correct.  This particular test is there for a very good reason.

The reason being that you should _not_ run the LG3 pipeline from the `${LG3_HOME}` folder.  If your setup requires that, then your setup is incorrect.  This is why I added it in the first place.  The reason is that it should be possible to run the pipeline without having write access to the `${LG3_HOME}` folder.  The solution is to set `LG3_HOME` correctly, which is described in <https://github.com/UCSF-Costello-Lab/LG3_Pipeline#installation-notes>.  FWIW, when using `module CBC lg3` on TIPCC, then this is automatically done for you, and that is also what we will do on C4.

**Comment by HenrikBengtsson** [comment]
This is also why you must no longer run under `/c4/home/jocostello/` and especially not using an account that is not yours.  So, please start running everything under your own account from now on.

**Comment by ivan108** [comment]
I have nothing against assert_pwd, my question was how to get read of SC2119 warning.
I see that you fixed it in scripts/utils.sh, thanks!
