### ISSUE TITLE
Pindel: SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-Costello-Lab/LG3_Pipeline#16]
I just received:

```sh
$ cat Patient157.pindel.err
'import site' failed; use -v for traceback
Traceback (most recent call last):
  File "/cbc/henrik/repositories/UCSF-CostelloLab/LG3_Pipeline/scripts/vcf2tdt.py", line 2, in <module>
    import sys, subprocess, re
  File "/opt/Python/Python-2.7.9/lib/python2.7/subprocess.py", line 1272
    closed = { None }
                    ^
SyntaxError: invalid syntax
```
and
```sh
$ tail Patient157.pindel.out
Reading chromosome chrM into memory.
Total reads: 7
Sorting completed
Removing chromosome chrM from memory.

Note: for this conversion, the -G (GATK) compatibility option was used; it's possible that this format is not compatible with other VCF-reading software. Also note that GATK requires genotypes to be 0/0, 0/1 or 1/1 instead of undefined, like ./1 or . ('not detected'). However, since pindel cannot yet genotype events (distinguish between 0/1 and 1/1) all events are called as 0/0 (not found) or 0/1, even while some may very well be homozygous alternative (1/1).


========= [Pindel] Convert vcf to tdt
ABORT: error on line 110
```

**Comment by ivan108** [comment]
Since I am not getting that error, it could be related to different python version.

The pipeline uses older /usr/bin/python : 

> /usr/bin/python --version
> Python 2.6.6

and I see you have Python-2.7.9 ...

**Comment by ivan108** [comment]
Not sure what we can do about pindel2vcf -G GATK compatibility mode. It was always there...

**Comment by HenrikBengtsson** [comment]
> Since I am not getting that error, it could be related to different python version. [...]

Interesting. The Python script (`scripts/vcf2tdt.py`) is called as an executable, which works because it has [a shebang](https://github.com/UCSF-Costello-Lab/LG3_Pipeline/blob/feature/envvars/scripts/vcf2tdt.py#L1).  The shebang is `#!/usr/bin/python`, so I'd also expect that Python 2.6.6 is used;
```r
$ /usr/bin/python --version
Python 2.6.6
```
but for some reason also Python 2.7.9 gets involved.

...

Ah... by `~/.bashrc` includes a `module load CBI python`, which sets the `PYTHONPATH`;
```lua
prepend_path("PYTHONPATH","/opt/Python/Python-2.7.9/lib/python2.7")
```

Ah 2. So, I should add a:
```sh
unset PYTHONPATH  ## ADHOC: In case it is set by user
```
as I had to do in [scripts/Align_fastq.sh](https://github.com/UCSF-Costello-Lab/LG3_Pipeline/blob/feature/envvars/scripts/Align_fastq.sh#L52).

Writing robust, sustainable, reproducible software is really tricky ... and lots of testing :p

**Comment by ivan108** [comment]
A quick question, in most shell scripts we have the following lines:

```
#$ -clear
#$ -S /bin/bash
#$ -cwd
#$ -j y
```
What does it do and do we need it??

**Comment by HenrikBengtsson** [comment]
Please avoid hijacking issues for unrelated purpose - instead, start a new issue for a new topic so we can stay sane and be able to close issues - issues are completely free ;)

**Comment by HenrikBengtsson** [comment]
I ended up doing `unset PYTHONPATH` is several locations;
```sh
$ grep -F "unset PYTHONPATH" *.pbs scripts/*.sh
pindel_all.pbs:unset PYTHONPATH  ## ADHOC: In case it is set by user. /HB 2018-09-13
scripts/Align_fastq.sh:unset PYTHONPATH  ## ADHOC: In case it is set by user. /HB 2018-09-07
scripts/MutDet.sh:unset PYTHONPATH  ## ADHOC: In case it is set by user /HB 2018-09-13
scripts/annotate_mutations_from_bam.sh:unset PYTHONPATH  ## ADHOC: In case it is set by user
scripts/combine_snvs.sh:unset PYTHONPATH  ## ADHOC: In case it is set by user
scripts/libID_to_patientID.sh:unset PYTHONPATH  ## ADHOC: In case it is set by user
scripts/mutation_overlaps.sh:unset PYTHONPATH  ## ADHOC: In case it is set by user
scripts/mutect_coverage_intersection_mutations.sh:unset PYTHONPATH  ## ADHOC: In case it is set by user
scripts/runLOH_ivan.sh:unset PYTHONPATH  ## ADHOC: In case it is set by user
```
