### ISSUE TITLE
Chastity filtering: Optional rather than dropping it?

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-Costello-Lab/LG3_Pipeline#20]
@ivan108 [wrote](https://github.com/UCSF-Costello-Lab/LG3_Pipeline/issues/15#issuecomment-420426463):
> I only modified scripts/Align_fastq.sh file, **removed chastity filtering of input fastq files**, because it is not compatible with fastqs extracted from bam, only with original Illumina fastqs...

Hmm... this isn't backward compatible with the production pipeline, correct?  If so, your breaking reproducibility if you rerun old samples.

I'll update (in features/envvars-t for now) to make this an optional step so that it will rename in production and when testing the full data set.

**Comment by ivan108** [comment]
Yes, we can make it optional for the sake of backward compatibility, but it will work only when we have original Illumina reads, it won't work with the reads extracted from the BAM files.
Another thing, already for many years now the fastq data is distributed already with chastity failed reads removed, so it became a useless step anyway...

**Comment by HenrikBengtsson** [comment]
I've made it optional (commit eefe8a3 by via environment variable `CHASTITY_FILTERING` which defaults to `true` for now:
```bash
CHASTITY_FILTERING=${CHASTITY_FILTERING:-true}
```

> Another thing, already for many years now the fastq data is distributed already with chastity failed reads removed, so it became a useless step anyway...

Got it.  I'll add it to the list to drop it in a future release.
