### ISSUE TITLE
Next release: Wrapping up another release

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-Costello-Lab/LG3_Pipeline#29]
@ivan108, just a heads up.  I'll freeze another version and release that one soon.  I've been testing the `develop` branch with the new tweaks using an account that also hits the newer compute nodes (e.g. n31 which Ziv Lab runs on).  Those machines are outliers in the sense that they have there own system library stack, but the good news is that: the LG3 Pipeline appears to work there as well.

**Comment by ivan108** [comment]
Got it...
I continue to work on merge, merge scripts are almost done, but recal2 need more work. And we don't have biologically sensible test set for merging scenario..

**Comment by HenrikBengtsson** [comment]
I've just released LG3_Pipeline version 2018-09-19, i.e. I pushed to tag '2018-09-19' and set the master branch to that.  The develop branch is also up-to-date and ready to take new commits.  Please do a `git pull` already now.
