### ISSUE TITLE
CHECKS: ShellCheck also FilterMutations/ files

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-Costello-Lab/LG3_Pipeline#33]
Run ShellCheck also on FilterMutations/ files

**Comment by ivan108** [comment]
But those are python scripts, AFAIK ShellCheck doesn't work with python??

**Comment by HenrikBengtsson** [comment]
There are also shell scripts.

FYI, there are probably tools for validation Python scripts too but I don't know that will enough. There are for R.
