### ISSUE TITLE
How to set actual raw data directory?

### ISSUE THREAD

**Issue by ivan108** [UCSF-Costello-Lab/LG3_Pipeline#34]
Trying:
```
_run_Trim
```

Getting 
```
[2018-09-19 16:08:07 PDT] BEGIN: ./_run_Trim
Call: ./_run_Trim
Script: ./_run_Trim
Arguments:
Input:
- LG3_HOME=/home/jocostello/shared/LG3_Pipeline
- LG3_INPUT_ROOT=/costellolab/data1/jocostello
- LG3_OUTPUT_ROOT=/costellolab/data1/jocostello
- EMAIL=ivan.smirnov@ucsf.edu
- DIROUT=
- TG=
- SAMPLES=Z00599t Z00600t Z00601t
Qsub extras:
- QSUB_OPTS=-d /home/jocostello/pp -M ivan.smirnov@ucsf.edu
- QSUB_ENVVARS=LG3_HOME=/home/jocostello/shared/LG3_Pipeline,LG3_OUTPUT_ROOT=/costellolab/data1/jocostello,EMAIL=ivan.smirnov@ucsf.edu
ETA ~4h
ERROR: Can't open Z00599t from /costellolab/data1/jocostello/
ERROR: Can't open Z00600t from /costellolab/data1/jocostello/
ERROR: Can't open Z00601t from /costellolab/data1/jocostello/
[2018-09-19 16:08:07 PDT] END: ./_run_Trim
```

Actual location of raw untrimmed Fastq files: /costellolab/data1/ismirnov/tmp

What is the "right way" to set the right $LG3_INPUT_ROOT? Just edit _run_Trim file?

**Comment by HenrikBengtsson** [comment]
If and only if set LG3_OUTPUT_ROOT (e.g. to ./output) then it will be automatically set in all scripts. For the first two steps it be ./rawdata otherwise to LG_OUTPUT_ROOT.

You can also set LG_INPUT_ROOT manually.

No need to edit scripts (and I think we should move toward being able to work with generic run scripts.

**Comment by ivan108** [comment]
I like the idea of not editing scripts, but I do have symbolic link 
rawdata -> /costellolab/data1/ismirnov/tmp
and it still doesn't work...

**Comment by HenrikBengtsson** [comment]
Ah... so when neither of those env vars are set, it should default to whatever you had before. HOWEVER, look at for instance _run_Trim line 11, I see that I used the wrong default for you. So my mistake 

(on a flight right now)

**Comment by ivan108** [comment]
What do we need DIROUT variable, how is it different from LG3_OUTPUT_ROOT?
Right now it is not set to anything...

**Comment by HenrikBengtsson** [comment]
It's a needed, legacy from the hardcoded paths. We should get rid of it though as soon as you've got the production pipeline to make work similar to the example (rather than relying on the legacy built-in defaults)

**Comment by HenrikBengtsson** [comment]
> I like the idea of not editing scripts, but I do have symbolic link
rawdata -> /costellolab/data1/ismirnov/tmp
and it still doesn't work...

Make sure you set LG3_OUTPUT_ROOT

**Comment by ivan108** [comment]
When you say "set LG3_OUTPUT_ROOT" you mean how? In .bashrc? But it is different for different stages..

**Comment by ivan108** [comment]
and we can't really avoid editing launching scripts, we need to put names of samples and patient and project. Unless we do a config file of some sort...

BTW, project (default LG3) supposed to be part of the output path, so that you can work on different projects in parallel without mixing outputs in the same directories...

**Comment by HenrikBengtsson** [comment]
Yeah, one day we might (re-)invent config files ... sounds familiar? ;)

**Comment by ivan108** [comment]
That is what I did in my "new" pipeline... :)

**Comment by HenrikBengtsson** [comment]
> When you say "set LG3_OUTPUT_ROOT" you mean how? In .bashrc? But it is different for different stages..

Look at the README example; doing `export LG3_OUTPUT_ROOT=output` (which btw `module load lg3` does) is all you need.  All steps output to `./output/`.  If you don't set `LG3_INPUT_ROOT` it'll default to `LG3_OUTPUT_ROOT` (i.e. to `output`) except for `_run_Trim` and `_run_Align_gz` where it will default to `rawdata`.  (This happens in the different `_run_*` scripts.

**Comment by HenrikBengtsson** [comment]
It looks like you've moved to using `rawdata/` as the new default for **run scripts**;
```sh
$ git checkout develop
$ grep -F rawdata *.pbs runs_demo/*
runs_demo/_run_Align_gz:    #LG3_INPUT_ROOT=${LG3_INPUT_ROOT:-rawdata}
runs_demo/_run_Align_gz:LG3_INPUT_ROOT=${LG3_INPUT_ROOT:-rawdata}
runs_demo/_run_Trim:    #LG3_INPUT_ROOT=${LG3_INPUT_ROOT:-rawdata}
runs_demo/_run_Trim:LG3_INPUT_ROOT=${LG3_INPUT_ROOT:-rawdata}
runs_demo/_run_Trim:LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-rawdata}
```
We should probably update the default for the corresponding PBS and shell scripts too;
```sh
$ grep -E "^LG3_OUTPUT_ROOT=[$]{" Align_*.pbs trim_galore.pbs scripts/Align*.sh scripts/trim_galore.sh
Align_bam.pbs:LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-/costellolab/data1/jocostello}
Align_fastq_mm9.pbs:LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-/costellolab/data1/jocostello}
Align_fastq.pbs:LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-/costellolab/data1/jocostello}
Align_fastq_vir.pbs:LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-/costellolab/data1/jocostello}
trim_galore.pbs:LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-/costellolab/data1/jocostello}
scripts/Align_bam.sh:LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-/costellolab/data1/jocostello}
scripts/Align_fastq_mm9.sh:LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-/costellolab/data1/jocostello}
scripts/Align_fastq.sh:LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-/costellolab/data1/jocostello}
scripts/Align_fastq_vir.sh:LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-/costellolab/data1/jocostello}
scripts/trim_galore.sh:LG3_OUTPUT_ROOT=${LG3_OUTPUT_ROOT:-/costellolab/data1/jocostello}
```
Are you ok with this?  That is, making `./rawdata/` the new default input/raw data folder?

**Comment by HenrikBengtsson** [comment]
FYI, I've [re-fixed the default `LG3_INPUT_ROOT` for _run_Align_gz](https://github.com/UCSF-Costello-Lab/LG3_Pipeline/commit/ad598507971a2c39978919365aa1163f53dc96bb#diff-1cedde7a3a04c952e22a7198556174af).  I think you missed my https://github.com/UCSF-Costello-Lab/LG3_Pipeline/issues/34#issuecomment-422993181 comment.
