### ISSUE TITLE
PROJECT variable

### ISSUE THREAD

**Issue by ivan108** [UCSF-Costello-Lab/LG3_Pipeline#35]
I am fixing/adding ${PROJECT} variable, which should be used instead of /LG3/ step in paths, e.g.
${LG3_INPUT_ROOT}/LG3/exomes  ==>  ${LG3_INPUT_ROOT}/${PROJECT}/exomes

This would allow to run multiple projects from the same location, without outputting into the same directories..

**Comment by HenrikBengtsson** [comment]
Thxs. Some related TODOs after doing a quick code inspection:

* [ ] Set PROJECT=${PROJECT:-LG3} in all PBS scripts - not just the run scripts.
* [ ] Assert PROJECT=${PROJECT:?} everywhere.

**Comment by ivan108** [comment]
OK, I will work on that in develop branch..

**Comment by ivan108** [comment]
I think I did it, check it out...

**Comment by HenrikBengtsson** [comment]
Looks good to me.

PS. I've just started a re-test on the develop branch commit 6b8cc1c, but please feel free to keep working on it.

**Comment by HenrikBengtsson** [comment]
Actually, it fails because we need to use `export PROJECT` before calling the corresponding `script/*.sh`, otherwise `PROJECT` will not be set when running the script.  This does not apply to some of the other env vars because there they are exported explicitly in our Torque/PBS calls.  I've updated the trim step (only) and testing that step right now:
```diff
$ diff --git a/trim_galore.pbs b/trim_galore.pbs
index 8d6f0f6..358062b 100755
--- a/trim_galore.pbs
+++ b/trim_galore.pbs
@@ -22,6 +22,7 @@ DIROUT=${DIROUT:-$(dirname "$FASTQ1")}
 
 ### Input
 echo "Input:"
+echo "- PROJECT=${PROJECT:?}"
 echo "- FASTQ1=${FASTQ1:?}"
 echo "- FASTQ2=${FASTQ2:?}"
 echo "- PREFIX=${PREFIX:?}"
@@ -73,6 +74,7 @@ echo "Current working directory: ${PWD}"
 cp "$FASTQ1" .
 cp "$FASTQ2" .
 
+export PROJECT
 "${SCRIPT}" -quality="$QTY" "$FASTQ1" "$FASTQ2" || { echo "ERROR: trim_galore FAILED"; exit 1; }
 
 FQ1=$(basename "$FASTQ1")
```

**Comment by ivan108** [comment]
So, it should go into .bashrc?
Also, I am not totally happy with variable name PROJECT, a bit too generic, may be LG3_PROJECT instead to continue your naming pattern?

**Comment by HenrikBengtsson** [comment]
> So, it should go into .bashrc?
No, see my diff.  It needs to be added to each PBS script.

> Also, I am not totally happy with variable name PROJECT, a bit too generic, may be LG3_PROJECT instead to continue your naming pattern?

I think `PROJECT` is fine, cf. `PREFIX`, `QTY`, etc.  The ones called `LG3_*` are more global/debug settings whose default values should rarely have to be modified; `LG3_HOME`, `LG3_OUTPUT_ROOT`, `LG3_DEBUG`.

Instead, I think makes more sense to eventually move to a config file (as you've done in your forked version) and/or support command-line options.  I think such a move will be easier when we've pruned off all hardcoded settings and defaults writing to the Costello Lab drives.

**Comment by HenrikBengtsson** [comment]
Ok, now I see... I should have been more clear.  The `PROJECT` environment variable should only be validated where it is used, e.g. it is _not_ used in the `scripts/trim_galore.sh` and therefore _not_ be validated there.  I'll undo these changes as I work my way through the test.

**Comment by HenrikBengtsson** [comment]
> I think PROJECT is fine, cf. PREFIX, QTY, etc. The ones called LG3_* are more global/debug settings whose default values should rarely have to be modified; LG3_HOME, LG3_OUTPUT_ROOT, LG3_DEBUG.

Following my own logic here, I should probably revert back to `CHASTITY_FILTERING` (from  `LG3_CHASTITY_FILTERING`).

**Comment by HenrikBengtsson** [comment]
Verified that it now works (after some tweaks).
