### ISSUE TITLE
TASK: Validate Bash scripts using ShellCheck on Travis CI

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-Costello-Lab/LG3_Pipeline#4]
TASKS:

* [x] Run simple ShellCheck test on all scripts
* [x] Add that test on Travis CI
* [x] Fix all ShellCheck warnings/errors
   - [x] *.pbs files
   - [x] scripts/*.sh files
* [ ] Validate through real tests

**Comment by ivan108** [comment]
Yes, I also see tons of SC2086 warnings.. I never double quote bash variables because I never use spaces in the variable values. But if you think it is a good style, I will correct that..


I never worked with git branches, so not totally comfortable, but I see your point.

________________________________

**Comment by HenrikBengtsson** [comment]
I've used ShellCheck in a few of my Bash-based projects and I've looked up some of the suggestions (e.g. https://github.com/koalaman/shellcheck/wiki/SC2086) and they basically all make sense and I can see how they're robustifying the code.

To work with branches, you can do:

1. `git checkout develop`
2. Do you edits, commits, pushes etc.
3. When you/we think we're ready to bring that into production, we do `git checkout master`, then `git merge develop`, and finally `git push`.

**Comment by HenrikBengtsson** [comment]
In my projects, I'm basically always in the develop branch (i.e. `git checkout develop`).  I rarely go over to the master branch - only for releasing new version.

**Comment by HenrikBengtsson** [comment]
To further clarify "how to work in develop branch": do `git clone ...` in a separate folder and work there.  Never work in the production folder (`/home/jocostello/shared/LG3_Pipeline/`).

**Comment by ivan108** [comment]
I see potential problem here. In our case the base path of the repository /home/jocostello/shared/LG3_Pipeline is hardcoded into scripts...

What do we do about that?

________________________________

**Comment by HenrikBengtsson** [comment]
Hmm... what's the problem? Is your question related to working in the develop branch vs master branch, or is it something else?  FYI, there's task https://github.com/UCSF-Costello-Lab/LG3_Pipeline/issues/3 for replacing hardcoded paths/strings with env variables (that can take the same default).

**Comment by ivan108** [comment]
For example we have a .pbs file in the develop branch, which calls the shell script with hardcoded path pointing to the file in production directory.

And then we modified shell script in develop, and launching pbs script from develop, but it will still call the shell scripts from production...

See what I mean?


Of course when we get read of hardcoded paths the problem will disappear..

________________________________

**Comment by HenrikBengtsson** [comment]
Ok, yes, the only way to actually *test* the code in the develop branch, you'll have to switch over to that one also in the production folder, e.g.

```sh
{~/LG3_Pipeline-developing}$ git push # push the new develop branch commits
{~/LG3_Pipeline-developing}$ cd /home/jocostello/shared/LG3_Pipeline
{/home/jocostello/shared/LG3_Pipeline}$ git checkout develop
{/home/jocostello/shared/LG3_Pipeline}$ git pull
{/home/jocostello/shared/LG3_Pipeline}$ <run tests>
{/home/jocostello/shared/LG3_Pipeline}$ git checkout master # switch back to stable production
```

When Issue #3 has been resolved, the above won't be necessary.

**Comment by HenrikBengtsson** [comment]
@ivan108, can I start working on these ShellCheck issues in parallel?  For instance, I can start updating from the bottom of the following list and do frequent commits/pushes:
```sh
$ ll *.pbs scripts/*.sh
-rwxr-xr-x 1 hb hb  455 Aug 29 10:23 Align_bam.pbs
-rwxr-xr-x 1 hb hb  862 Aug 29 10:23 Align_fastq_mm9.pbs
-rwxr-xr-x 1 hb hb  859 Aug 29 10:23 Align_fastq.pbs
-rwxr-xr-x 1 hb hb  653 Aug 29 10:23 Align_fastq_vir.pbs
-rwxr-xr-x 1 hb hb  726 Aug 29 10:23 Annotate_RNA.pbs
-rwxr-xr-x 1 hb hb  565 Aug 29 10:23 fastqc.pbs
-rwxr-xr-x 1 hb hb  814 Aug 29 10:23 Germline_only.pbs
-rwxr-xr-x 1 hb hb  922 Aug 29 10:23 Germline.pbs
-rwxr-xr-x 1 hb hb  226 Aug 29 10:23 HybridSelect.pbs
-rwxr-xr-x 1 hb hb  599 Aug 29 10:23 Merge.pbs
-rwxr-xr-x 1 hb hb  612 Aug 29 10:23 Merge_QC.pbs
-rwxr-xr-x 1 hb hb 1570 Aug 29 10:23 MutDet_TvsN.pbs
-rwxr-xr-x 1 hb hb 2464 Aug 29 10:23 pindel_all.pbs
-rwxr-xr-x 1 hb hb 2425 Aug 29 10:23 pindel_wgs.pbs
-rwxr-xr-x 1 hb hb 1004 Aug 29 10:23 Post_align.pbs
-rwxr-xr-x 1 hb hb 2688 Aug 29 10:23 post_mutect_pindel.pbs
-rwxr-xr-x 1 hb hb 1319 Aug 29 10:23 Recal_bigmem.pbs
-rwxr-xr-x 1 hb hb 1345 Aug 29 10:23 Recal_merge1.pbs
-rwxr-xr-x 1 hb hb 1362 Aug 29 10:23 Recal_merge_fixmate.pbs
-rwxr-xr-x 1 hb hb 1354 Aug 29 10:23 Recal_merge.pbs
-rwxr-xr-x 1 hb hb  614 Aug 29 10:23 Recal_only.pbs
-rwxr-xr-x 1 hb hb 1201 Aug 29 10:23 Recal_pass2.pbs
-rwxr-xr-x 1 hb hb 1292 Aug 29 10:23 Recal.pbs
-rwxr-xr-x 1 hb hb 1388 Aug 29 10:23 Recal_QC.pbs
-rwxr-xr-x 1 hb hb 1365 Aug 29 10:23 Recal_split.pbs
-rwxr-xr-x 1 hb hb  722 Aug 29 10:23 Recal_WGS.pbs
-rwxr-xr-x 1 hb hb  733 Aug 29 10:23 Recal_WGS_QC.pbs
-rwxr-xr-x 1 hb hb 3690 Aug 29 10:23 scripts/Align_bam.sh
-rwxr-xr-x 1 hb hb 3680 Aug 29 10:23 scripts/Align_fastq_mm9.sh
-rwxr-xr-x 1 hb hb 3668 Aug 29 10:23 scripts/Align_fastq.sh
-rwxr-xr-x 1 hb hb 3717 Aug 29 10:23 scripts/Align_fastq_vir.sh
-rwxr-xr-x 1 hb hb  423 Aug 29 10:23 scripts/annotate_mutations_from_bam.sh
-rwxr-xr-x 1 hb hb 1242 Aug 29 10:23 scripts/Annotate_RNA.sh
-rwxr-xr-x 1 hb hb 1720 Aug 29 10:23 scripts/chk_mutdet.sh
-rwxr-xr-x 1 hb hb  516 Aug 29 10:23 scripts/chk_pindel.sh
-rwxr-xr-x 1 hb hb  326 Aug 29 10:23 scripts/combine_snvs.sh
-rwxr-xr-x 1 hb hb  175 Aug 29 10:23 scripts/fastqc.sh
-rwxr-xr-x 1 hb hb 1654 Aug 29 10:23 scripts/FixReadGroups.sh
-rwxr-xr-x 1 hb hb 4815 Aug 29 10:23 scripts/Germline.sh
-rwxr-xr-x 1 hb hb 1234 Aug 29 10:23 scripts/HybridSelect.sh
-rwxr-xr-x 1 hb hb  412 Aug 29 10:23 scripts/libID_to_patientID.sh
-rwxr-xr-x 1 hb hb 3639 Aug 29 10:23 scripts/Merge_QC.sh
-rwxr-xr-x 1 hb hb 2329 Aug 29 10:23 scripts/Merge.sh
-rwxr-xr-x 1 hb hb  365 Aug 29 10:23 scripts/mutation_overlaps.sh
-rwxr-xr-x 1 hb hb 2571 Aug 29 10:23 scripts/MutContext.sh
-rwxr-xr-x 1 hb hb 9840 Aug 29 10:23 scripts/MutDet.sh
-rwxr-xr-x 1 hb hb 2665 Aug 29 10:23 scripts/mutdet_submit.sh
-rwxr-xr-x 1 hb hb 2070 Aug 29 10:23 scripts/mutdet_submit_wgs.sh
-rwxr-xr-x 1 hb hb  707 Aug 29 10:23 scripts/mutect_coverage_intersection_mutations.sh
-rwxr-xr-x 1 hb hb 5051 Aug 29 10:23 scripts/pindel_annotate.sh
-rwxr-xr-x 1 hb hb  424 Aug 29 10:23 scripts/pindel_filter.sh
-rwxr-xr-x 1 hb hb  243 Aug 29 10:23 scripts/pindel_setup.sh
-rwxr-xr-x 1 hb hb  247 Aug 29 10:23 scripts/pindel_wgs_setup.sh
-rwxr-xr-x 1 hb hb 2363 Aug 29 10:23 scripts/Post_align.sh
-rwxr-xr-x 1 hb hb 1743 Aug 29 10:23 scripts/QC_hs.sh
-rwxr-xr-x 1 hb hb 7971 Aug 29 10:23 scripts/Recal_bigmem.sh
-rwxr-xr-x 1 hb hb 6995 Aug 29 10:23 scripts/Recal_merge1.sh
-rwxr-xr-x 1 hb hb 6764 Aug 29 10:23 scripts/Recal_merge_fixmate.sh
-rwxr-xr-x 1 hb hb 5444 Aug 29 10:23 scripts/Recal_merge.sh
-rwxr-xr-x 1 hb hb 7773 Aug 29 10:23 scripts/Recal_pass2.sh
-rwxr-xr-x 1 hb hb 3701 Aug 29 10:23 scripts/Recal_QC.sh
-rwxr-xr-x 1 hb hb 7822 Aug 29 10:23 scripts/Recal.sh
-rwxr-xr-x 1 hb hb 3952 Aug 29 10:23 scripts/Recal_split.sh
-rwxr-xr-x 1 hb hb 4676 Aug 29 10:23 scripts/Recal_Table.sh
-rwxr-xr-x 1 hb hb 1503 Aug 29 10:23 scripts/Recal_WGS_QC.sh
-rwxr-xr-x 1 hb hb 5966 Aug 29 10:23 scripts/Recal_WGS.sh
-rwxr-xr-x 1 hb hb 8371 Aug 29 10:23 scripts/Rob-MutDet-hg18.sh
-rwxr-xr-x 1 hb hb  714 Aug 29 10:23 scripts/runLOH_ivan.sh
-rwxr-xr-x 1 hb hb 1118 Aug 29 10:23 scripts/trim_galore.sh
-rwxr-xr-x 1 hb hb 4168 Aug 29 10:23 scripts/UG.sh
-rwxr-xr-x 1 hb hb 1037 Aug 29 10:23 trim_galore.pbs
-rwxr-xr-x 1 hb hb  431 Aug 29 10:23 UG.pbs
```

**Comment by ivan108** [comment]
That is fine, except I already fixed a few files from scripts directory:
Align_bam.sh
Align_fastq.sh
annotate_mutations_from_bam.sh
combine_snvs.sh
fastqc.sh
UG.sh -- currently modifiying ...

**Comment by HenrikBengtsson** [comment]
Ok, I'll start working on the *.pbs scripts then.  When you're done for the day, please commit and push - or just frequently.

**Comment by ivan108** [comment]
Sounds good!

**Comment by HenrikBengtsson** [comment]
I've now fixed all *.pbs scripts (in develop branch).

**Comment by HenrikBengtsson** [comment]
@ivan108 wrote:
> OK, all bash scripts in "scripts" directory are fixed. Love shellcheck!!!

Great. I've temporarily added `--exclude=SC1091` to the ShellCheck tests so that `make check` passes on Travis CI.
