### ISSUE TITLE
Rename runs_demo/patient_ID_conversions.txt to *.tsv

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-Costello-Lab/LG3_Pipeline#42]
To clarify the file format, filename extension `*.tsv` should be used for `runs_demo/patient_ID_conversions.*`.

**Comment by ivan108** [comment]
agree, *.tsv more accurately reflects file format...

**Comment by HenrikBengtsson** [comment]
Ok. Done in all files using:
```sh
sed -i 's|patient_ID_conversions.txt|patient_ID_conversions.tsv|g' *.pbs scripts/*.sh tests/* scripts/*.py runs_demo/* README.md run_chk_data 
```

**Comment by HenrikBengtsson** [comment]
FYI, using *.tsv also has the nice side effect that it is rendered as a table on GitHub;

https://github.com/UCSF-Costello-Lab/LG3_Pipeline/blob/develop/runs_demo/patient_ID_conversions.tsv
