### ISSUE TITLE
CLEANUP: Drop absolute path to R/Rscript - instead assume they're on the PATH

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-Costello-Lab/LG3_Pipeline#48]
I've looked through all the script/*.R scripts, I'm 99.9% certain that they work with any version of R. In other words, we should be able to drop the fixed location /opt/R/R-latest/bin/ and rely on R / Rscript being on the path. We could assert with
```sh
{ which Rscript &> /dev/null; } || { echo "ERROR: ..."; exit 1; }
```

Related to: Issue #10.

**Comment by ivan108** [comment]
I am (almost) pretty sure R version doesn't matter, but I think we should stick to some fixed version, may be one of the latest?
The reason Rscript path was added in the past, it was because computing nodes didn't see any R...

**Comment by HenrikBengtsson** [comment]
> The reason Rscript path was added in the past, it was because computing nodes didn't see any R...

That must have been for the older cluster prior to Scyld-based TIPCC.  Now all nodes should have identical setup.

I'd say that we should avoid freezing version of core language tools such as R (*), Python, and Java if possible. That just complicates installation and migration of the pipeline.  Instead, it's better to identify the supported versions and provide a list of requirements, e.g. R (>= 3.2.0) etc.

(*) I know for a fact that R is very backward compatible.

**Comment by ivan108** [comment]
I see your point,
but I am afraid the ancient GATK version we are using only works with JAVA6...

**Comment by HenrikBengtsson** [comment]
> the ancient GATK version we are using only works with JAVA6...

Ok, so then we have a Java (<= 6) requirement to list.  We can also add sanity checks to make sure that that version is actual used, e.g. based on the output of `java -version`.

**Comment by HenrikBengtsson** [comment]
Closing since Rscript is no longer specified with an absolute path.  The Java version dependency is tracked in #166.
