### ISSUE TITLE
Making repository public?

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-Costello-Lab/LG3_Pipeline#5]
Can we make this LG3_Pipeline public on GitHub so that we can run automatic tests on it on Travis CI?

**Comment by ivan108** [comment]
OK, it is public now...

________________________________

**Comment by HenrikBengtsson** [comment]
Thxs. I'll go ahead an setup the Travis CI automatic ShellCheck testing now.

**Comment by ivan108** [comment]
It seems admin permissions are needed to do that...

________________________________

**Comment by ivan108** [comment]
?? I think it worked before...

________________________________

**Comment by HenrikBengtsson** [comment]
@ivan108, try to comment via the GitHub website rather than replying to emails - then you'll get to correct order of the comments and you'll get them in a live fashion (there's a slight delay in email notifications).

> ?? I think it worked before...
You only had 'Write' authority to the GitHub repos before. I'm pretty sure you need 'Admin' authority to switch between private and public.
