### ISSUE TITLE
lg3 test validate: Doesn't support change of PROJECT

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-Costello-Lab/LG3_Pipeline#51]
```sh
$ lg3 test validate
*** Configuration
[OK] Project: LG3-another
[OK] Patient: Patient157t
[OK] Truth: /costellolab/data1/shared/LG3_Pipeline/example_data/truth

*** Trimmed FASTQ files
ERROR: No such folder: /costellolab/data1/shared/LG3_Pipeline/example_data/truth/output/LG3-another/trim
```

The reason is obvious.  The "truth" path should do a `$PROJECT` -> `LG3` replacement.

**Comment by ivan108** [comment]
I am not sure pipeline validation should be associated with any PROJECT?? It is a part of the pipeline, isn't it?

**Comment by HenrikBengtsson** [comment]
Sure, but I wanted test that all steps actually handle a non default value of PROJECT.

Anyway, the fix something be easy. I'll do it later.

**Comment by HenrikBengtsson** [comment]
I've not fixed this.  By running the tests with `PROJECT=LG3-another`, I discovered that `scripts/runMAF.py` did not acknowledge `PROJECT` but instead hardcoded the input to be `.../LG3/...` which in turn caused a lot of silent errors and empty output.  I fixed that too.
