### ISSUE TITLE
WISH: Pull 'SAMPLES' from (PATIENT, CONV file)

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-Costello-Lab/LG3_Pipeline#56]
> Ideally, it should be enough just to provide patient_ID_conversions.tsv file and PATIENT id, as is done in the later steps of mutation calling..

That is, it should not be needed to specify `SAMPLES`.

**Comment by ivan108** [comment]
.. nor NORMAL

**Comment by HenrikBengtsson** [comment]
Great.  I just borrowed from this to have `lg3 test setup` report:
```sh
$ lg3 test setup
*** Setup
[OK] PROJECT: LG3
[OK] PATIENT: Patient157t10 (required for 'lg3 test validate')
[OK] CONV: patient_ID_conversions.tsv
[OK]   => SAMPLES: Z00599t10 Z00600t10 Z00601t10  (required by '_run_Recal')
[OK]   => NORMAL: 'Z00599t10' (required by '_run_Recal')
[...]
```

**Comment by ivan108** [comment]
I added in some other places sample extraction from CONV table...

**Comment by HenrikBengtsson** [comment]
I see you've done lots of nice updates these last few days :)

FYI, there are two more (PATIENT, CONV) updates remaining:
```sh
$ grep -F Z00 runs_demo/_run_*
runs_demo/_run_Merge:SAMPLES=${SAMPLES:-Z00600t10 Z00601t10}
runs_demo/_run_Merge_QC:SAMPLES=${SAMPLES:-Z00600t10 Z00601t10}
```

**Comment by ivan108** [comment]
Thanks :)
Actually _run_Merge[_QC] requires hand picked samples, not all samples from the patient.

**Comment by HenrikBengtsson** [comment]
For the record, replicating what I just commented on in Issue #68:

Verified: I've run through the tests for the new defaults (Patient157t10) using a fairly recent develop version:
```
$ (cd $LG3_HOME; git log -1)
commit cd0b563a2dfe1d246b9f2abd6bdbddd43584657b (HEAD -> develop, origin/develop)
Author: hb <hb@aroma-project.org>
Date:   Wed Oct 10 19:33:45 2018 -0700

    Use new default 'Patient157t10' also in help/examples
```
and all went well.
