### ISSUE TITLE
NOTES: Speed up of "Creation intervals for indel detection" (GATK RealignerTargetCreator)

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-Costello-Lab/LG3_Pipeline#63]
(Migrating to its own issue)

@ivan108 [wrote on 2018-10-01](https://github.com/UCSF-Costello-Lab/LG3_Pipeline/issues/53#issuecomment-426071402):

Since Recal script call multiple scripts, I added timing to all calls. Here what I got:

```
Patient157t ncores=12  vmem=200gb
8m55.635s   Merge BAM files
0m46.880s   Index new BAM file
590m19.804s Create intervals for indel detection [-Xmx8g]
23m58.556s  Fix mate information
21m18.772s  Mark duplicates
0m36.945s   Index BAM file
17m9.715s   Base-quality recalibration: Count covariates
173m7.998s  Base-quality recalibration: Table Recalibration
1m15.925s   Index BAM file
17m24.010s  Split BAM files
6m53.127s   Splitting off Z00599t
7m7.839s    Splitting off Z00600t
5m32.271s   Splitting off Z00601t
0m26.315s   Calculate flag statistics Z00599t
1m28.623s   Calculate hybrid selection metrics Z00599t
3m22.342s   Collect multiple QC metrics Z00599t
```
As we can see "Create intervals for indel detection" is the main bottleneck, takes 10h(!)
Couple of things we can try:
1. Increase memory for Java above 8GB (job requests 200GB)
2. Increase number of threads above 12
3. Add target interval list

and [followed up with](https://github.com/UCSF-Costello-Lab/LG3_Pipeline/issues/53#issuecomment-426388831):

So, I did increase java memory to -Xmx64G [ed. `-Xmx64g`] and added target interval list.
Result: improved timing from 629m20.545s to 157m56.530s ! 
[ed. begin: this was done in commit 2fa9cc1]
```diff
 echo -e "\\n[Recal] Create intervals for indel detection..."
-{ time $JAVA -Xmx64g -Djava.io.tmpdir="${TMP}" \
+{ time $JAVA -Xmx8g -Djava.io.tmpdir="${TMP}" \
         -jar "$GATK" \
         --analysis_type RealignerTargetCreator \
         --reference_sequence "$REF" \
         --known "$THOUSAND" \
-                 -L "${ilist}" \
         --num_threads "${ncores}" \
         --logging_level WARN \
         --input_file "${patientID}.merged.bam" \
```
[ed. end]
This is a great improvement, and I suspect mostly because of the adding target list.
We are already using the "target list", in some mutation calling steps, this is the same list.
"Target list" is the list of genomic intervals, it is used to limit GATK and Picard calculations to only those genomic intervals. The list is typically provided by sequencing facility, it is platform specific, and it represents exomes targeted by the library construction probes. Alternatively the list of all known exomes can be used instead. Theoretically there should not be any reads outside those targeted intervals, so it should be kosher to limit GATK to those intervals. In reality, there is always some amount of the off-target reads, which would be lost for analysis. That is why they usually add some 100-200bp margins to those intervals.
Hope it makes sense :)

Then @HenrikBengtsson [confirmed the speedup](https://github.com/UCSF-Costello-Lab/LG3_Pipeline/issues/53#issuecomment-426527708):

I've just reran it with these new tweaks. I've now got that New Recal takes 6h10m versus prev Recal took 14h30m (on 10% dataset).

**Comment by HenrikBengtsson** [comment]
I've updated `lg3 test validate` to also report on the diff of the first 10 columns of the final mutation table, if and only if there's a diff.  Here's that diff, which helps seeing the difference:
```sh
[WARN] unexpected file content ('output/LG3/MutInDel/Patient157t10.R.mutations')
--- /dev/fd/63  2018-10-03 08:30:26.200208762 -0700
+++ /dev/fd/62  2018-10-03 08:30:26.200208762 -0700
@@ -1,0 +2,3 @@
+NOS2   chr17   26089902        A       G       T2722C  Y908H   exonic  Missense        covered_in_all
+CLEC4M,CLEC4M  chr19   7830800 G       A       G338A,G491A,G422A,G491A,G419A,G407A,G491A,G428A R113Q,R164Q,R141Q,R164Q,R140Q,R136Q,R164Q,R143Q exonic;splicing Missense        covered_in_all
+DOCK6  chr19   11348348        C       G       G1940C  G647A   exonic  Missense        covered_in_all
@@ -3 +5,0 @@
-EPN3   chr17   48618382        C       T       C1208T  A403V   exonic  Missense        covered_in_all
@@ -5,2 +7 @@
-DOCK6  chr19   11348348        C       G       G1940C  G647A   exonic  Missense        covered_in_all
-NOS2   chr17   26089902        A       G       T2722C  Y908H   exonic  Missense        covered_in_all
+EPN3   chr17   48618382        C       T       C1208T  A403V   exonic  Missense        covered_in_all
```

The `+CLEC4M,CLEC4M  chr19   7830800 G       A` mutation is now picked up.  I guess it makes sense; by guing GATK where to look ... and not to look ... we should get more power.

**Comment by HenrikBengtsson** [comment]
Interesting.  It could be that memory doesn't matter that much and you're only seeing a random discrepancy due to other loads on the same machine or other I/O to the same disk(s).

Alternatively, it could be related to the whole issue of Java garbage-collector threads consuming all resources and that there could be a cost for using way more memory than needed.  It might be that various race conditions kick in.  I don't know - just a wild guess.

**Comment by HenrikBengtsson** [comment]
Forgot to say, either way, it sounds like the main performance gain comes from specifying the regions (option `-L`).  Do you agree?

**Comment by ivan108** [comment]
I agree. And it is supported by some posts on the net..

**Comment by HenrikBengtsson** [comment]
Great.  My belief (read "hope") is that by specifying the regions, we:

* significantly speed up the processing, and
* we gain more power (higher true positive rate at a given false positive rate) in detecting mutation.

So, a win-win, with no downsides (except that the findings of already processed samples would have been slightly different).

**Comment by HenrikBengtsson** [comment]
So, this should also be added to the Recal_pass2 step, correct?

**Comment by ivan108** [comment]
Yes, will do..

**Comment by ivan108** [comment]
done

**Comment by ivan108** [comment]
Another experiment, increased number of cores to 24, no effect! (137min)
