### ISSUE TITLE
Speedup of MuTect

### ISSUE THREAD

**Issue by ivan108** [UCSF-Costello-Lab/LG3_Pipeline#67]
I checked if our ancient MuTect supports multi-threading, and it does!
So, I added -nt $ncores option, as a result  execution time decreased from 97min down to 35 min using 4 cores! Increasing ncores to 8 only marginally improved the speed (31min). The tests were done with Patient157t10.

**Comment by HenrikBengtsson** [comment]
Awesome.

**Comment by HenrikBengtsson** [comment]
Looks good to me and tests still work
