### ISSUE TITLE
TESTS: Run tests on Patient157t10 (new default)

### ISSUE THREAD

**Issue by ivan108** [UCSF-Costello-Lab/LG3_Pipeline#68]
Suggestions

Switch test to the smallest input files (Patient157t10)

**Comment by HenrikBengtsson** [comment]
The Subject of this issue does not match the comment, or vice verse.

**Comment by HenrikBengtsson** [comment]
FYI, you can edit Issue subject in GitHub.

**Comment by ivan108** [comment]
Good to know :)

**Comment by HenrikBengtsson** [comment]
Verified: I've run through the tests for the new defaults (Patient157t10) using a fairly recent develop version:
```
$ (cd $LG3_HOME; git log -1)
commit cd0b563a2dfe1d246b9f2abd6bdbddd43584657b (HEAD -> develop, origin/develop)
Author: hb <hb@aroma-project.org>
Date:   Wed Oct 10 19:33:45 2018 -0700

    Use new default 'Patient157t10' also in help/examples
```
and all went well.
