### ISSUE TITLE
Issues trying to submit multiple samples from a file in _run_Trim

### ISSUE THREAD

**Issue by shuntsman-ucsf** [UCSF-Costello-Lab/LG3_Pipeline#69]
I ran into a roadblock trying to convert the _run_Trim script to use a file list of input prefixes instead of requiring the sample names to be hardcoded inside the script. 

I only made a few changes in this version.

old: 
`SAMPLES=${SAMPLES:-Z00599t Z00600t Z00601t}`
new:
`SAMPLES=("cat $LG3_INPUT_ROOT/tumNorm_preFixListTest.txt")`
*there should be back-single-quote characters around the cat command above, but github views it as code markup, so I used " here

Then down where it loops through the samples to submit:

old:
`for PREFIX in ${SAMPLES}`
`do`
 `  FASTQ1=${LG3_INPUT_ROOT}/${PREFIX}_R1.fastq.gz`
 `  FASTQ2=${LG3_INPUT_ROOT}/${PREFIX}_R2.fastq.gz`
`...`

new:
`for PREFIX in "${SAMPLES[@]}" `
`do`
 `  FASTQ1=${LG3_INPUT_ROOT}/${PREFIX}_R1_001_HQ_paired.fastq.gz`
`   FASTQ2=${LG3_INPUT_ROOT}/${PREFIX}_R2_001_HQ_paired.fastq.gz`
`...`

I know the prefix is getting read from the file and passed to the "for" loop correctly, but the FASTQ1 and FASTQ2 variables are not getting declared correctly including the input_root and prefix.  I don't do much shell scripting so maybe there is something simple that is wrong with what I changed, but I can't see it. The rest of the script aside from the above changes remains the same.

After the FASTQ1= declaration, 
`echo $FASTQ1`
_R1_001_HQ_paired.fastq.gz0_fastq/SC299834_AACGTGAT_L001
which looks like the PREFIX is being put after the suffix and no INPUT_ROOT, along with some extra characters.

**Comment by HenrikBengtsson** [comment]
> `SAMPLES=("cat $LG3_INPUT_ROOT/tumNorm_preFixListTest.txt")`
> *there should be back-single-quote characters around the cat command above, but github views it as code markup, so I used " here

Google `markdown backtick` for this particular problem.  But, much better and easier is to use Markdown fenced code block; see ['Styling with Markdown']( https://guides.github.com/features/mastering-markdown/ ) link below each comment field here in GitHub.  It provides the basics of Markdown.

Now, to the actual problem.  In Bash, an expression such as:
```sh
SAMPLES=${SAMPLES:-Z00599t Z00600t Z00601t}
```
means "assign `"Z00599t Z00600t Z00601t"` to env var `SAMPLES` _unless_ `SAMPLES` is already defined".  In other words, you can set `SAMPLES` before calling the script, e.g.
```sh
export SAMPLES="Z132 Z133 Z134"
```
and then there's no need to modify (at least) that run script.   This way you can play around with:
```sh
export SAMPLES=$(cat $LG3_INPUT_ROOT/tumNorm_preFixListTest.txt)
echo "SAMPLES=${SAMPLES}"
```
to make sure that `SAMPLES` is really set to what you expect.

_Comment:_ `$(call ...)` is the preferred way in Bash, preferred over ``(`call ...`)``.

The whole mixup of prefix-suffix doesn't make sense to me; my best guess is that `SAMPLES` is not what you think.

**Comment by HenrikBengtsson** [comment]
Did you resolve this one?  If so, please report back what you did and close when resolved.

**Comment by HenrikBengtsson** [comment]
Ping?

**Comment by shuntsman-ucsf** [comment]
Thanks for tip to pass args from outside script, but I still haven't gotten a clean "read lines from file" as args solution to work, hence why I haven't closed issue.  I've done similar in PERL tons of times, but haven't figured out in shell yet.  Also, there was a problem with my _trim jobs that I just found out, will be posting new issue soon.

**Comment by HenrikBengtsson** [comment]
I'm closing this one since (i) the `SAMPLES` environment variable should not really be used anymore, (ii) it should now be resolved by using a patient file instead, and (iii) your problems figuring out how to parse a text file into a Bash array/string is not really related to the LG3 pipeline.

**Comment by ivan108** [comment]
I agree that  default for SAMPLES should be all samples listed in CONV table for a patient.
But sometimes you may want to exclude some samples, e.g. a known bad sample, or if there are too many samples you may want to pre-process them in batches (trimming and alignment). So, it is good to be able to overwrite defaults SAMPLES values when you launch job...
