### ISSUE TITLE
ROBUSTNESS: Relay errors in more places

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-Costello-Lab/LG3_Pipeline#77]
For instance, in `Recal_bigmem.pbs`, errors are [not relayed](https://github.com/UCSF-Costello-Lab/LG3_Pipeline/blob/master/Recal_bigmem.pbs#L75) from `scripts/Recal_bigmem.sh`; just silently ignored:
```sh
SCRIPT_A=${LG3_HOME}/scripts/Recal_bigmem.sh
...
"${SCRIPT_A}" "$BAMS" "$PATIENT" "$ILIST"
```
This should really be
```sh
"${SCRIPT_A}" "$BAMS" "$PATIENT" "$ILIST" || { echo "ERROR: Failed to ..."; exit 1 }
```
to produce an error as soon as possible and prevent further processing.  It looks like several scripts could/should be improved this way.

**Comment by ivan108** [comment]
Yes, we need to check exit status of all steps, and abort it right away..

**Comment by ivan108** [comment]
Recal_bigmem.pbs:
added exit status check to SCRIPT_A and SCRIPT_B.

**Comment by HenrikBengtsson** [comment]
I found a few more cases from manual inspect and fixed them.  I'll assume everything is fixed now, but lets keep an eye out.
