### ISSUE TITLE
Markdown formatting

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-Costello-Lab/LG3_Pipeline#8]
@ivan108, install [vmd](https://github.com/yoshuawuyts/vmd) so you can preview your *.md files without having to push the to GitHub first;
```sh
$ vmd README.md
```
It'll automatically refresh whenever the file is updated.

I have it running on Ubuntu 18.04, but it is cross-platform AFAIK.

**Comment by ivan108** [comment]
That would be great, but I don't have any Linux at home, only Mac and Windows...

**Comment by HenrikBengtsson** [comment]
> I have it running on Ubuntu 18.04, **but it is cross-platform AFAIK**.

It works at least also on macOS

**Comment by ivan108** [comment]
I found one MD editor for MacOSX called Mou. It works great, but sometimes it is more forgiving than the one on github. Anyway, Readme_demo.md looks much better now, thanks!

**Comment by HenrikBengtsson** [comment]
Great. FYI, some editors have options for various Markdown flavors.
