### ISSUE TITLE
Check errors

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-Costello-Lab/LG3_Pipeline#85]
@ivan108, don't forget to run `make check` and/or keep an eye on https://travis-ci.org/UCSF-Costello-Lab/LG3_Pipeline:

```sh
$ make check
[...]
In Recal_pass2.pbs line 86:
ls -1 ./*.bwa.realigned.rmDups.* | grep -v recal | mk_links
^-- SC2010: Don't use ls | grep. Use a glob or a for loop with a condition to allow non-alphanumeric filenames.
```

**Comment by ivan108** [comment]
Actually I saw that, just didn't figure out how to exclude some files *recal* from the initial selected listing. How would you do it?

**Comment by HenrikBengtsson** [comment]
Either one consider the current code safe and adds a ShellCheck directive to ignore [SC2010](https://github.com/koalaman/shellcheck/wiki/SC2010):
```sh
# ShellCheck disable=SC2010
ls -1 ./*.bwa.realigned.rmDups.* | grep -v recal
```
or could use `find`, e.g.
```sh
find . -maxdepth 1 -type f -name "*.bwa.realigned.rmDups.*" -not -name "*quality*" | mk_links
```
This finds all _files_ (not directories) in the current directory (no recursive scan) that match the filename criterias.  I think that would work.

SC2010 says parsing `ls` output is unsafe.

**Comment by ivan108** [comment]
Great, that works! Thanks for the tip...
