### ISSUE TITLE
Updating NEWS

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-Costello-Lab/LG3_Pipeline#86]
@ivan108, please try to add an entry to the [NEWS.md](https://github.com/UCSF-Costello-Lab/LG3_Pipeline/blob/develop/NEWS.md) file, when you make a change is worth mentioning, e.g. changing default `vmem` from 100gb to 64gb.  I've been trying to catch up and add these in past, but to lower the risk for missing something, please try to add them yourself.

**Comment by ivan108** [comment]
Done
