### ISSUE TITLE
Remove `bigmem` resource request from PBS script

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-Costello-Lab/LG3_Pipeline#87]
Several \*.pbs scripts have PBS declarations that request `bigmem` nodes, e.g.
```sh
#PBS -l nodes=1:bigmem:ppn=12,vmem=200gb
```
Do we really need that?  I would think specifying `mem/vmem` would take care of that.  I don't know the history of `bigmem` but it could be a legacy from old times.

Having `bigmem` in there could prevent a job from ending up on a non-`bigmem` nodes if one would submit the PBS script with say `qsub  -l nodes=1:ppn=6,vmem=50gb ...`

**Comment by ivan108** [comment]
Good point, I think we can remove "bigmem"... 
Do you know how many bigmem and "smallmem" nodes are available e.g. for Costello lab?

**Comment by HenrikBengtsson** [comment]
Ok, let's plan on removing that.

1. I don't there's such a thing as a `smallmem` resource/node; a node is flagged as either `bigmem` or not.
2. You can run `pbsnodes | grep -E "(^n[0-9]+|big|small)"` on the cluster to see which nodes have the `bigmem` flag. See https://ucsf-ti.github.io/tipcc-web/about/specs.html for which nodes Costello Lab has access to.

**Comment by ivan108** [comment]
Removed!

**Comment by HenrikBengtsson** [comment]
Related to this, @shuntsman-ucsf, did you manage to drop `bigmem` using `qalter` on TIPCC?  If not, we can do a quick release of the current develop version where `bigmem` is no longer used.

**Comment by ivan108** [comment]
what is `qalter` ?? 
I did remove it from *.pbs files...

**Comment by HenrikBengtsson** [comment]
Sounds like those `qalter` calls of yours caused any `bigmem`:s to be dropped.  Good.  Then we don't need to rush out a new release.
