### ISSUE TITLE
CHECK ERROR: Invalid path in develop branch

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-Costello-Lab/LG3_Pipeline#97]
In the last release round, I added `make check` assertions that we don't hardcode toward various folders on TIPCC.  This will allow us to eventually get to a point where the pipeline will run outside of TIPCC.

Somewhere in `develop` it looks like a `/home/jocostello/shared/LG3_Pipeline` (I think) sneaked into the code:

```sh
$ git checkout master
$ make check
Miscellaneous code inspections:
- Assert no hardcoded email address
- Assert no /data/.. paths
- Assert no /costellolab/.. paths
- Assert no /home/jocostello/shared/LG3_Pipeline
- Assert no /home/jocostello/.. paths
shellcheck *.pbs
shellcheck bin/lg3*
shellcheck FilterMutations/*.sh
shellcheck -x scripts/*.sh
shellcheck runs_demo/_run_*
```

```sh
$ git checkout develop
$ make check
Miscellaneous code inspections:
- Assert no hardcoded email address
- Assert no /data/.. paths
- Assert no /costellolab/.. paths
- Assert no /home/jocostello/shared/LG3_Pipeline
Makefile:23: recipe for target 'check_misc' failed
make: *** [check_misc] Error 1
```

PS. Please keep an eye on https://travis-ci.org/UCSF-Costello-Lab/LG3_Pipeline - I also get email notifications from Travis when builds fail.

**Comment by HenrikBengtsson** [comment]
Thxs. The error is now of different kind - see https://travis-ci.org/UCSF-Costello-Lab/LG3_Pipeline/jobs/444432857#L381-L383
```sh
In Recal_step.pbs line 82:
cp -p ${RECOVER_DIR}/* . || { echo "ERROR cp!" ; exit 1 ; }
      ^-- SC2086: Double quote to prevent globbing and word splitting.
```

**Comment by ivan108** [comment]
OK, fixed SC error, but still fail check:

```
make check
Miscellaneous code inspections:
- Assert no hardcoded email address
- Assert no /data/.. paths
- Assert no /costellolab/.. paths
- Assert no /home/jocostello/shared/LG3_Pipeline
make: *** [check_misc] Error 1
```

???

**Comment by HenrikBengtsson** [comment]
Since Travis all OK now, you must have an offending files locally.

Drop `-q` in the grep call to see the matches (instead of only setting the exit code)

**Comment by ivan108** [comment]
Fixed
