### ISSUE TITLE
Error when running MutDet "invalid -v syntax"

### ISSUE THREAD

**Issue by shuntsman-ucsf** [UCSF-Costello-Lab/LG3_Pipeline#98]
Error when submitting, getting "invalid -v syntax" from something in mutdet_submit.sh
I don't see any other output or error files, so this is all I have:
```
[2018-10-24 10:55:44 PDT] BEGIN: ./_run_MutDet_edit
Call: ./_run_MutDet_edit
Script: ./_run_MutDet_edit
Arguments:
Input:
- LG3_HOME=/home/shared/cbc/software_cbc/LG3_Pipeline-2018-10-17
- LG3_INPUT_ROOT=output
- LG3_OUTPUT_ROOT=/zivlab/data2/tumorNormal
- EMAIL=s--
- PATIENT=COH-001
- PROJECT=LG3
- CONV=patient_ID_conversions_merged.tsv
Submitting jobs for COH-001 Wed Oct 24 10:55:44 PDT 2018
[2018-10-24 10:55:44 PDT] BEGIN: /home/shared/cbc/software_cbc/LG3_Pipeline-2018-10-17/scripts/mutdet_submit.sh
Call: /home/shared/cbc/software_cbc/LG3_Pipeline-2018-10-17/scripts/mutdet_submit.sh
Script: /home/shared/cbc/software_cbc/LG3_Pipeline-2018-10-17/scripts/mutdet_submit.sh
Arguments: COH-001 /zivlab/data2/tumorNormal/LG3/patient_ID_conversions_merged.tsv LG3
Settings:
- LG3_HOME=/home/shared/cbc/software_cbc/LG3_Pipeline-2018-10-17
- LG3_INPUT_ROOT=output
- LG3_OUTPUT_ROOT=output
- EMAIL=s--
- LG3_SCRATCH_ROOT=/scratch/shuntsman/
- PWD=/home/shuntsman/gh/lg3-test
- USER=shuntsman
Qsub extras:
- QSUB_OPTS= -d /home/shuntsman/gh/lg3-test -M s--
- QSUB_ENVVARS=LG3_HOME=/home/shared/cbc/software_cbc/LG3_Pipeline-2018-10-17,LG3_INPUT_ROOT=output,LG3_OUTPUT_ROOT=output,EMAIL=s--
Input:
- PROJECT=LG3
- CONV=/zivlab/data2/tumorNormal/LG3/patient_ID_conversions_merged.tsv
- PATIENT=COH-001
References:
- CONFIG=/home/shared/cbc/software_cbc/LG3_Pipeline-2018-10-17/FilterMutations/mutationConfig.cfg
- INTERVAL=/home/shared/cbc/software_cbc/LG3_Pipeline-2018-10-17/resources/All_exome_targets.extended_200bp.interval_list
invalid -v syntax
invalid -v syntax
[2018-10-24 10:55:44 PDT] END: /home/shared/cbc/software_cbc/LG3_Pipeline-2018-10-17/scripts/mutdet_submit.sh
[2018-10-24 10:55:44 PDT] END: ./_run_MutDet_edit
```

**Comment by HenrikBengtsson** [comment]
Probably related to invalid `EMAIL`;

```
- EMAIL=s--
```

**Comment by shuntsman-ucsf** [comment]
Sorry, I should have noted, I only removed the email for posting on the web, actual run has valid email.

**Comment by HenrikBengtsson** [comment]
Ok. Next question, why/what's changed in `_run_MutDet_edit`? There shouldn't be a needed to edit the run scripts.

**Comment by shuntsman-ucsf** [comment]
I edit the patient-id and I changed the conversion table to one that includes the merged tumors, "patient_ID_conversions_merged.tsv" since it is a different file than what is needed by the first recal.  That is all.  I'm wondering if anything in the `INTERVAL=/home/shared/cbc/software_cbc/LG3_Pipeline-2018-10-17/resources/All_exome_targets.extended_200bp.interval_list` file is conflicting with our data but not with the demo data?

**Comment by HenrikBengtsson** [comment]
> I edit the patient-id and I changed the conversion table to one that includes the merged tumors, "patient_ID_conversions_merged.tsv" since it is a different file than what is needed by the first recal. That is all.

Oh. It's always better to avoid editing/tweaking code unless you really have to.  No matter how small the edit is, there's always a risk of a teeny bug sneaking in that way.  So, instead of customizing your own script, the intended way is to use:
```sh
$ export PATIENT=Foo123
$ export CONV=new/file.tsv
$ ./_run_MutDet
```
or, in a single call, use:
```sh
$ PATIENT=Foo123 CONV=new/file.tsv ./_run_MutDet
```

> I'm wondering if anything in the `INTERVAL=/home/shared/cbc/software_cbc/LG3_Pipeline-2018-10-17/resources/All_exome_targets.extended_200bp.interval_list` file is conflicting with our data but not with the demo data?

I don't think this is the reason for the error "invalid -v syntax", because it looks like it  stems from the following line in [`scripts/mutdet_submit.sh`](https://github.com/UCSF-Costello-Lab/LG3_Pipeline/blob/2018-10-17/scripts/mutdet_submit.sh#L119):
```sh
qsub ${QSUB_OPTS} -N "Mut_${PATIENT}" -v "${QSUB_ENVVARS},PROJECT=${PROJECT},NORMAL=${normid},TUMOR=${ID},TYPE=${samp_label},PATIENT=${PATIENT},CONFIG=$CONFIG,INTERVAL=$INTERVAL,WORKDIR=$WORKDIR,XMX=$XMX" "$PBS"
```

That is, there's something funny going on in the
```sh
"${QSUB_ENVVARS},PROJECT=${PROJECT},NORMAL=${normid},TUMOR=${ID},TYPE=${samp_label},PATIENT=${PATIENT},CONFIG=$CONFIG,INTERVAL=$INTERVAL,WORKDIR=$WORKDIR,XMX=$XMX"
```
string.

**Comment by HenrikBengtsson** [comment]
I've added LG3_Pipeline 2017-10-17-patched to TIPCC;
```sh
$ module load lg3/2018-10-17-patched
$ lg3 --version
2018-10-17-patched
```
It reports also on `NORMAL`, `TUMOR` and `TYPE` inferred from the `CONV` file.  I suspect that one of those could be invalid.  So use that patched version instead and share the new output.

**Comment by shuntsman-ucsf** [comment]
I edited my own version of mutdet_submit.sh to include some extra debugging echo statements and see the following values immediately before the qsub call in question:
```
...
References:
- CONFIG=/home/shared/cbc/software_cbc/LG3_Pipeline-2018-10-17/FilterMutations/mutationConfig.cfg
- INTERVAL=/home/shared/cbc/software_cbc/LG3_Pipeline-2018-10-17/resources/All_exome_targets.extended_200bp.interval_list
qsubenvars=
project=LG3
Normal=
tumor=SC299834_AACGTGAT_L001
type=TUM
pat=COH-001
config=/home/shared/cbc/software_cbc/LG3_Pipeline-2018-10-17/FilterMutations/mutationConfig.cfg
interv=/home/shared/cbc/software_cbc/LG3_Pipeline-2018-10-17/resources/All_exome_targets.extended_200bp.interval_list
workdir=output/LG3/mutations/COH-001_mutect
xmx=Xmx8g
pbs=/home/shared/cbc/software_cbc/LG3_Pipeline-2018-10-17/MutDet_TvsN.pbs
invalid -v syntax
qsubenvars=
project=LG3
Normal=
tumor=SC299981_merged
type=TUM
pat=COH-001
config=/home/shared/cbc/software_cbc/LG3_Pipeline-2018-10-17/FilterMutations/mutationConfig.cfg
interv=/home/shared/cbc/software_cbc/LG3_Pipeline-2018-10-17/resources/All_exome_targets.extended_200bp.interval_list
workdir=output/LG3/mutations/COH-001_mutect
xmx=Xmx8g
pbs=/home/shared/cbc/software_cbc/LG3_Pipeline-2018-10-17/MutDet_TvsN.pbs
invalid -v syntax
[2018-10-25 00:17:05 PDT] END: /home/shuntsman/gh/lg3-test/mutdet_submit_edit.sh
[2018-10-25 00:17:05 PDT] END: ./_run_MutDet_edit
```
Will look into it more tomorrow, but I notice that it seems to cycle through it twice and labels 2 separate tumors even though the first value listed "SC299834_AACGTGAT_L001" should be a normal based on the conversion file.

**Comment by HenrikBengtsson** [comment]
I've updated 2018-10-17-patched to assert that `NORMAL`, `TUMOR` and `TYPE` are non-empty.  At least that gives an earlier error.

The code that identifies the normal, is:

https://github.com/UCSF-Costello-Lab/LG3_Pipeline/blob/4c95f1cbb87145cf0f7eda1057d93ff50b2f5e0a/scripts/mutdet_submit.sh#L80-L87

It could be that you don't have TABs, too many TABs, ...

**Comment by shuntsman-ucsf** [comment]
I manually edited the file in nano to make sure it only had 1 tab between fields and newline at the end of each line in case it was a windows excel formatting type error, but still having problem.

I placed an echo $SAMP statement right above the` if [ "$SAMP" = "Normal" ]` conditional above and it outputs `Normal`, yet it never registers as true and never enters within the conditional to set normid.

The first few lines of my patient_conversions file look like:
```
lib_ID  SF      patient_ID      sample_type
SC299834_AACGTGAT_L001  NA      COH-001 Normal
SC299981_merged NA      COH-001 Primary
SC299842_AAACATCG_L001  NA      COH-002 Normal
SC299989_merged NA      COH-002 Primary
SC299858_AGTGGTCA_L003  NA      COH-004 Normal
SC300013_merged NA      COH-004 Primary
```

**Comment by shuntsman-ucsf** [comment]
I changed both instances of `if [ "$SAMP" = "Normal" ]` to `if["${SAMP:0:3}" = "Nor"]` to be similar to the other tumor type checks in mutdet_submit.sh, and it now seems to be working.  There must be some hidden formatting at the end of line that is not being handled, which makes me wonder why the tumors are treated differently to avoid that issue already by only checking first few characters.

**Comment by HenrikBengtsson** [comment]
Ok, so if `["${SAMP:0:3}" = "Nor"]` solves it, you most likely have funny/extra whitespace in your TSV file.  

> which makes me wonder why the tumors are treated differently to avoid that issue already by only checking first few characters.

I don't know the history, but I doubt that it was to protect against mistakes in the input file.  It's always better to fix the source of the problem (but code should at least detect and give informative errors).

I've created Issue #100 to validate TSV files.

**Comment by HenrikBengtsson** [comment]
The problem is that you have CRLF (`\r\n`) line endings instead of LF (`\n`) line endings.  This is because you edited the TSV file on Windows.   You can use `dos2unix` to fix that.

**Comment by HenrikBengtsson** [comment]
I've added support for CRLF line endings in the patched version, please retry with:
```sh
$ module load lg3/2018-10-17-patched
$ lg3 --version
2018-10-17-patched
```

It's important that you move away from your own solution already now, if not, we're risking end up ingin troubleshooting hell if you're running your own patch.

**Comment by shuntsman-ucsf** [comment]
Just tried the new patched version with my conversion table, seems to solve the problem.  Thanks.

**Comment by HenrikBengtsson** [comment]
FYI, you can see whether you have CRs (= `^M` below) in your line endings by using [`less -U`](https://twitter.com/henrikbengtsson/status/1055612198762893317):
```sh
$ less -XF -U $CONV
lib_ID^ISF^Ipatient_ID^Isample_type^M
SC299834_AACGTGAT_L001^INA^ICOH-001^INormal^M
SC299981_merged^INA^ICOH-001^IPrimary^M
SC299842_AAACATCG_L001^INA^ICOH-002^INormal^M
[...]
```
Your TABs are `^I`.
